export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_LOCKED: "PLAN_LOCKED",
  PLAN_NOT_SUBMITTED: "PLAN_NOT_SUBMITTED",
  PLAN_STATE_INVALID: "PLAN_STATE_INVALID",
  REJECT_REASON_REQUIRED: "REJECT_REASON_REQUIRED",
  DAMAGE_NOT_FOUND: "DAMAGE_NOT_FOUND",
  DAMAGE_IN_RESTORATION: "DAMAGE_IN_RESTORATION"
} as const;
