export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PLAN_NOT_FOUND: "PLAN_NOT_FOUND",
  PLAN_NOT_SUBMITTED: "PLAN_NOT_SUBMITTED",
  PLAN_APPROVAL_REASON_REQUIRED: "PLAN_APPROVAL_REASON_REQUIRED",
  PLAN_LOCKED: "PLAN_LOCKED",
  DAMAGE_NOT_FOUND: "DAMAGE_NOT_FOUND",
  DAMAGE_ALREADY_IN_RESTORATION: "DAMAGE_ALREADY_IN_RESTORATION",
  DAMAGE_HAS_PLAN: "DAMAGE_HAS_PLAN"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
